/**
 * Generates calendar.ics — a subscribable iCalendar feed of MHR practices —
 * from data/workouts.json.
 *
 * The feed is "current + upcoming only": it mirrors whatever is in
 * workouts.json, which the admin console replaces each week. Subscribers do
 * not keep past practices. Nothing is accumulated or archived here.
 *
 * Format mirrors data/races.ics (generated by mhr-race-agent) so the two feeds
 * stay consistent, with RFC 5545 conformance fixes: TZID/VTIMEZONE instead of
 * baked-in UTC, full text escaping, and 75-octet line folding.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const TZID = 'America/Denver';
const CAL_NAME = 'Mile High Runners Training';
const CAL_DESC = 'Group workouts for Mile High Runners — Erie, Colorado';
const FEED_URL = 'https://milehighrunners.com/calendar.ics';
const PAGE_URL = 'https://milehighrunners.com/calendar.html';
const PRODID = '-//Mile High Runners//Workout Calendar//EN';
const REFRESH = 'PT4H';
const ALARM_MINUTES = 45;

// No end time exists in the source data. Weekday speed sessions run about an
// hour; the Saturday group run is longer.
const DEFAULT_DURATION_MINUTES = 60;
const SATURDAY_DURATION_MINUTES = 90;

// America/Denver: MST (-0700) / MDT (-0600), US DST rules.
const VTIMEZONE = [
    'BEGIN:VTIMEZONE',
    `TZID:${TZID}`,
    `X-LIC-LOCATION:${TZID}`,
    'BEGIN:DAYLIGHT',
    'TZOFFSETFROM:-0700',
    'TZOFFSETTO:-0600',
    'TZNAME:MDT',
    'DTSTART:19700308T020000',
    'RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU',
    'END:DAYLIGHT',
    'BEGIN:STANDARD',
    'TZOFFSETFROM:-0600',
    'TZOFFSETTO:-0700',
    'TZNAME:MST',
    'DTSTART:19701101T020000',
    'RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU',
    'END:STANDARD',
    'END:VTIMEZONE',
];

/** Escapes a text value per RFC 5545 section 3.3.11. */
function escapeText(value) {
    return String(value == null ? '' : value)
        .replace(/\\/g, '\\\\')
        .replace(/;/g, '\\;')
        .replace(/,/g, '\\,')
        .replace(/\r\n|\r|\n/g, '\\n');
}

/**
 * Folds a content line to 75 octets per RFC 5545 section 3.1. Counts bytes,
 * not characters, and never splits a multi-byte UTF-8 sequence — workout
 * descriptions routinely contain en-dashes.
 */
function foldLine(line) {
    const bytes = Buffer.from(line, 'utf8');
    if (bytes.length <= 75) {
        return line;
    }

    const parts = [];
    let start = 0;
    let limit = 75; // first line gets 75 octets, continuations 74 (leading space)

    while (start < bytes.length) {
        let end = Math.min(start + limit, bytes.length);
        // Back off if we landed inside a UTF-8 continuation byte (10xxxxxx).
        while (end > start && end < bytes.length && (bytes[end] & 0xc0) === 0x80) {
            end--;
        }
        parts.push(bytes.slice(start, end).toString('utf8'));
        start = end;
        limit = 74;
    }

    return parts.join('\r\n ');
}

/** Parses a 12-hour time string ("5:00 AM", "6:30 PM"). Returns null if unparseable. */
function parseTime12h(value) {
    const match = /^\s*(\d{1,2}):(\d{2})\s*([AaPp])\.?[Mm]\.?\s*$/.exec(String(value || ''));
    if (!match) {
        return null;
    }

    let hour = Number(match[1]);
    const minute = Number(match[2]);
    const isPm = match[3].toLowerCase() === 'p';

    if (hour < 1 || hour > 12 || minute > 59) {
        return null;
    }
    if (hour === 12) {
        hour = 0;
    }
    if (isPm) {
        hour += 12;
    }

    return { hour, minute };
}

/** Builds the human-facing event title. */
function eventTitle(workout) {
    const name = workout.location && workout.location.name;
    return name ? `MHR Practice — ${name}` : 'MHR Practice';
}

/**
 * Stable per-event UID: sha1(title|date|time). Deliberately excludes the
 * description and address so that editing the workout text or fixing an
 * address updates the event in place rather than orphaning it.
 */
function eventUid(workout) {
    const key = `${eventTitle(workout)}|${workout.date}|${workout.time}`;
    return `${crypto.createHash('sha1').update(key, 'utf8').digest('hex')}@milehighrunners.com`;
}

/** Formats a local date-time as an iCalendar DATE-TIME (no zone suffix; TZID carries the zone). */
function formatLocal(year, month, day, hour, minute) {
    const pad = (n) => String(n).padStart(2, '0');
    return `${year}${pad(month)}${pad(day)}T${pad(hour)}${pad(minute)}00`;
}

/** Formats a Date as a UTC iCalendar DATE-TIME. */
function formatUtc(date) {
    return `${date.toISOString().replace(/[-:]/g, '').split('.')[0]}Z`;
}

function durationMinutes(year, month, day) {
    // Date.UTC avoids any local-timezone drift on the day-of-week lookup.
    const isSaturday = new Date(Date.UTC(year, month - 1, day)).getUTCDay() === 6;
    return isSaturday ? SATURDAY_DURATION_MINUTES : DEFAULT_DURATION_MINUTES;
}

/** Renders one workout as VEVENT lines, or null if it can't be represented. */
function buildEvent(workout, dtstamp) {
    const dateMatch = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(workout.date || ''));
    if (!dateMatch) {
        return null;
    }
    const time = parseTime12h(workout.time);
    if (!time) {
        return null;
    }

    const year = Number(dateMatch[1]);
    const month = Number(dateMatch[2]);
    const day = Number(dateMatch[3]);

    const start = formatLocal(year, month, day, time.hour, time.minute);
    const endMinutes = time.hour * 60 + time.minute + durationMinutes(year, month, day);
    // Practices never run past midnight, so a same-day end is always correct.
    const end = formatLocal(year, month, day, Math.floor(endMinutes / 60) % 24, endMinutes % 60);

    const cancelled = workout.cancelled === true;
    const title = eventTitle(workout);
    const summary = cancelled ? `CANCELLED — ${title}` : title;

    const descriptionParts = [];
    if (cancelled) {
        descriptionParts.push(workout.cancellation_reason || 'This practice has been cancelled.');
    }
    if (workout.description) {
        descriptionParts.push(workout.description);
    }
    descriptionParts.push(`Details: ${PAGE_URL}`);

    const location = workout.location || {};
    const locationText = [location.name, location.address].filter(Boolean).join(', ');

    const lines = [
        'BEGIN:VEVENT',
        `UID:${eventUid(workout)}`,
        `DTSTAMP:${dtstamp}`,
        `DTSTART;TZID=${TZID}:${start}`,
        `DTEND;TZID=${TZID}:${end}`,
        `SUMMARY:${escapeText(summary)}`,
        `DESCRIPTION:${escapeText(descriptionParts.join('\n\n'))}`,
    ];

    if (locationText) {
        lines.push(`LOCATION:${escapeText(locationText)}`);
    }
    if (location.map_link) {
        lines.push(`URL;VALUE=URI:${location.map_link}`);
    }

    lines.push(`STATUS:${cancelled ? 'CANCELLED' : 'CONFIRMED'}`);
    lines.push('TRANSP:OPAQUE');
    lines.push('CATEGORIES:Running,Practice');

    // No point reminding someone about a practice that isn't happening.
    // Google ignores VALARM in subscribed feeds; Apple honors it.
    if (!cancelled) {
        lines.push(
            'BEGIN:VALARM',
            `TRIGGER:-PT${ALARM_MINUTES}M`,
            'ACTION:DISPLAY',
            `DESCRIPTION:${escapeText(`${title} in ${ALARM_MINUTES} minutes`)}`,
            'END:VALARM'
        );
    }

    lines.push('END:VEVENT');
    return lines;
}

/**
 * Builds the full calendar. `now` is injectable so tests get a fixed DTSTAMP.
 * Returns { ics, included, skipped }.
 */
function buildCalendar(workouts, now = new Date()) {
    const dtstamp = formatUtc(now);
    const skipped = [];

    const sorted = [...(workouts || [])].sort((a, b) => {
        const byDate = String(a.date).localeCompare(String(b.date));
        if (byDate !== 0) {
            return byDate;
        }
        const timeA = parseTime12h(a.time);
        const timeB = parseTime12h(b.time);
        if (!timeA || !timeB) {
            return 0;
        }
        return timeA.hour * 60 + timeA.minute - (timeB.hour * 60 + timeB.minute);
    });

    const eventLines = [];
    let included = 0;

    for (const workout of sorted) {
        const event = buildEvent(workout, dtstamp);
        if (event) {
            eventLines.push(...event);
            included++;
        } else {
            skipped.push(`${workout.date} ${workout.time}`);
        }
    }

    const lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        `PRODID:${PRODID}`,
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH',
        `NAME:${escapeText(CAL_NAME)}`,
        `X-WR-CALNAME:${escapeText(CAL_NAME)}`,
        `DESCRIPTION:${escapeText(CAL_DESC)}`,
        `X-WR-CALDESC:${escapeText(CAL_DESC)}`,
        `X-WR-TIMEZONE:${TZID}`,
        // Both forms: REFRESH-INTERVAL is RFC 7986, X-PUBLISHED-TTL is what
        // Apple and Outlook actually read. Google ignores both.
        `REFRESH-INTERVAL;VALUE=DURATION:${REFRESH}`,
        `X-PUBLISHED-TTL:${REFRESH}`,
        `SOURCE;VALUE=URI:${FEED_URL}`,
        ...VTIMEZONE,
        ...eventLines,
        'END:VCALENDAR',
    ];

    return {
        ics: lines.map(foldLine).join('\r\n') + '\r\n',
        included,
        skipped,
    };
}

/**
 * True when the two feeds differ in something a subscriber would notice.
 * DTSTAMP changes on every run; ignoring it keeps the workflow from
 * committing a no-op diff.
 */
function hasMeaningfulChange(previousIcs, nextIcs) {
    const strip = (ics) =>
        String(ics || '')
            .split(/\r?\n/)
            .filter((line) => !line.startsWith('DTSTAMP:'))
            .join('\n');
    return strip(previousIcs) !== strip(nextIcs);
}

module.exports = {
    escapeText,
    foldLine,
    parseTime12h,
    eventTitle,
    eventUid,
    buildCalendar,
    hasMeaningfulChange,
    TZID,
    CAL_NAME,
    FEED_URL,
};

// Run as script when executed directly
if (require.main === module) {
    const inputFile = path.join(__dirname, '../data/workouts.json');
    const outputFile = path.join(__dirname, '../calendar.ics');

    if (!fs.existsSync(inputFile)) {
        console.error(`Workouts file not found: ${inputFile}`);
        process.exit(1);
    }

    try {
        const workouts = JSON.parse(fs.readFileSync(inputFile, 'utf8'));
        if (!Array.isArray(workouts)) {
            console.error('Expected data/workouts.json to contain an array.');
            process.exit(1);
        }

        const { ics, included, skipped } = buildCalendar(workouts);

        if (skipped.length > 0) {
            console.warn(`Skipped ${skipped.length} workout(s) with unparseable date/time: ${skipped.join('; ')}`);
        }

        const previous = fs.existsSync(outputFile) ? fs.readFileSync(outputFile, 'utf8') : '';
        if (!hasMeaningfulChange(previous, ics)) {
            console.log('calendar.ics is already up to date.');
            process.exit(0);
        }

        fs.writeFileSync(outputFile, ics);
        console.log(`Updated calendar.ics with ${included} events.`);
    } catch (err) {
        console.error('Error generating calendar.ics:', err);
        process.exit(1);
    }
}
