name: MHR Gallery Docker Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mhr-gallery/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mhr-gallery/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: mhr-website-runner

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: kubernetes
        buildkitd-config-inline: |
          [registry."registry.local-registry.svc.cluster.local:5000"]
            insecure = true

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./mhr-gallery
        push: true
        tags: registry.local-registry.svc.cluster.local:5000/mhr-gallery:latest
